# Generated by Django 2.1.7 on 2019-03-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticles',
            options={'ordering': ('title',)},
        ),
    ]
